// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvgUCqB5381ZeBspm1aum-5Kepx9DkDHs',
    appId: '1:360161037435:android:d13a4e0fe20a39eb0aa6de',
    messagingSenderId: '360161037435',
    projectId: 'englit-999d9',
    storageBucket: 'englit-999d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcjAwZW-DkW3QItW28izK5NBN80JUi9xg',
    appId: '1:360161037435:ios:8ea7370ae3bb0e1d0aa6de',
    messagingSenderId: '360161037435',
    projectId: 'englit-999d9',
    storageBucket: 'englit-999d9.firebasestorage.app',
    androidClientId: '360161037435-aktpe628mnklpc6mtaqqam6u8hi3ide5.apps.googleusercontent.com',
    iosClientId: '360161037435-8dr5dd69splpkok442dnp7mut4h7cqbb.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

}